# Common settings

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

# Blocks reader settings

Db:
    AzureDataConnString:
        settings-key: Ripple-AzureDataConnString
        types:
            - AzureTableStorage
    LogsConnString:
        settings-key: Ripple-LogsConnString
        types:
            - AzureTableStorage
    MaxTransactionsSavingParallelism:
        settings-key: Ripple-MaxTransactionsSavingParallelism

RabbitMq:
    ConnString:
        settings-key: Bcn-BlocksReader-RabbitConnString
        types:
            - RabbitMq
    TransactionsBatchSize:
        settings-key: Ripple-TransactionsBatchSize
    Vhost:
        settings-key: Bcn-BlocksReader-RabbitVhost
        types:
            - Optional

# 4 by default

    MessageConsumersCount:
        settings-key: Bcn-BlocksReader-MessageConsumersCount
        types:
            - Optional

# 8 by default

    MessageProcessorsCount:
        settings-key: Bcn-BlocksReader-MessageProcessorsCount
        types:
            - Optional
    
# "00:00:30" by default

    DefaultFirstLevelRetryTimeout:
        settings-key: Bcn-BlocksReader-DefaultFirstLevelRetryTimeout
        types:
            - Optional

# "00:10:00" by default

    MaxFirstLevelRetryMessageAge:
        settings-key: Bcn-BlocksReader-MaxFirstLevelRetryMessageAge
        types:
            - Optional

# 20 by default

    MaxFirstLevelRetryCount:
        settings-key: Bcn-BlocksReader-MaxFirstLevelRetryCount
        types:
            - Optional

# 1000 by default

    FirstLevelRetryQueueCapacity:
        settings-key: Bcn-BlocksReader-FirstLevelRetryQueueCapacity
        types:
            - Optional

# 500 by default

    ProcessingQueueCapacity:
        settings-key: Bcn-BlocksReader-ProcessingQueueCapacity
        types:
            - Optional

LastIrreversibleBlockMonitoringPeriod:
    settings-key: Ripple-BlocksReader-LastIrreversibleBlockMonitoringPeriod
    types:
        - Optional

NodeRpcUrl:
    settings-key: Ripple-NodeRpcUrl
NodeRpcUsername:
    settings-key: Ripple-NodeRpcUsername
    types:
        - Optional
NodeRpcPassword:
    settings-key: Ripple-NodeRpcPassword
    types:
        - Optional