# Common settings

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

# Blocks reader settings

Db:
    AzureDataConnString:
        settings-key: Ripple-AzureDataConnString
        types:
            - AzureTableStorage
    LogsConnString:
        settings-key: Ripple-LogsConnString
        types:
            - AzureTableStorage

RabbitConnString:
    settings-key: Ripple-BlocksReader-RabbitConnString
    types:
        - RabbitMq
        
MessageListeningParallelism:
    settings-key: Ripple-BlocksReader-MessageListeningParallelism

LastIrreversibleBlockMonitoringPeriod:
    settings-key: Ripple-BlocksReader-LastIrreversibleBlockMonitoringPeriod
    types:
        - Optional

NodeRpcUrl:
    settings-key: Ripple-NodeRpcUrl
NodeRpcUsername:
    settings-key: Ripple-NodeRpcUsername
    types:
        - Optional
NodeRpcPassword:
    settings-key: Ripple-NodeRpcPassword
    types:
        - Optional